/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bres_line_alg;

import java.applet.Applet;
import java.awt.Color;
import java.awt.*;

/**
 *
 * @author Mazedul Islam
 */
public class Bres_Line_Alg extends Applet {

    /**
     * Creates new form Bres_Line_Alg
     */
    public void paint(Graphics g) {

        int x1 = 10, x2 = 300;
        int y1 = 30, y2 = 400;
        int dx = Math.abs(x2 - x1);
        int dy = Math.abs(y2 - y1);
        int p;
        int x, y;

        x = x1;
        y = y1;
        p = 2 * dy - dx;

        try {

            g.fillOval(x, y, 10, 10);

            for (int k = 0; k < dx; k++) {
                if (p < 0) {
                    g.fillOval(x++, y, 5, 5);
                    p = p + 2 * dy;

                } else {
                    g.fillOval(x++, y++, 5, 5);
                    p = p + 2 * (dy + dx);
                }

            }
            g.fillOval(x, y, 10, 10);
            
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
